const SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS recordings (
    id              TEXT PRIMARY KEY,
    source          TEXT NOT NULL,
    source_id       TEXT NOT NULL,
    genus           TEXT NOT NULL,
    species         TEXT NOT NULL,
    subspecies      TEXT DEFAULT '',
    common_name     TEXT DEFAULT '',
    lat             REAL,
    lng             REAL,
    elev_m          REAL,
    quality         TEXT,
    sound_type      TEXT,
    date            TEXT,
    time            TEXT,
    country         TEXT DEFAULT '',
    location        TEXT DEFAULT '',
    recordist       TEXT DEFAULT '',
    license         TEXT DEFAULT '',
    duration_s      REAL,
    sample_rate     INTEGER,
    remarks         TEXT DEFAULT '',
    provenance_json TEXT DEFAULT '{}',
    audio_path      TEXT,
    downloaded      INTEGER DEFAULT 0,
    created_at      TEXT NOT NULL,
    UNIQUE(source, source_id)
)
"""
